{{- $externalSecrets := default dict .Values.secrets.externalSecrets -}}
{{- $secretStore := default dict $externalSecrets.secretStore -}}
{{- if and $externalSecrets.enabled $secretStore.create }}
apiVersion: external-secrets.io/v1
kind: {{ default "SecretStore" $secretStore.kind }}
metadata:
  name: {{ required "secrets.externalSecrets.secretStore.name is required" $secretStore.name }}
  {{- if ne (default "SecretStore" $secretStore.kind) "ClusterSecretStore" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  {{- toYaml (required "secrets.externalSecrets.secretStore.spec is required" $secretStore.spec) | nindent 2 }}
{{- end }}
