{{- $externalSecrets := default dict .Values.secrets.externalSecrets -}}
{{- if $externalSecrets.enabled }}
{{- range $target := default (list) $externalSecrets.targets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "secrets.externalSecrets.targets[].name is required" $target.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "zipline-orchestration.labels" $ | nindent 4 }}
spec:
  {{- toYaml (required "secrets.externalSecrets.targets[].spec is required" $target.spec) | nindent 2 }}
{{- end }}
{{- end }}
