apiVersion: networking.k8s.io/v1
kind: Ingress
{{- $evalPath := default "/" (trimSuffix "/" (.Values.ingress.eval.path | default "/")) }}
metadata:
  name: eval-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.eval.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.eval.className }}
  rules:
    {{- if .Values.ingress.eval.host }}
    - host: {{ .Values.ingress.eval.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          {{- if eq $evalPath "/" }}
          - path: /
            pathType: Prefix
          {{- else }}
          - path: {{ printf "%s(/|$)(.*)" $evalPath | quote }}
            pathType: ImplementationSpecific
          {{- end }}
            backend:
              service:
                name: eval-service
                port:
                  number: 80
