apiVersion: v2
name: zipline-orchestration
description: Kubernetes deployment chart for Zipline Orchestration and Crucible compute
type: application
version: 0.3.4
appVersion: "0.9.7"

keywords:
  - zipline
  - orchestration
  - workflow
  - crucible
  - kubernetes

home: https://zipline.ai

maintainers:
  - name: Zipline AI
    email: support@zipline.ai

dependencies:
  - name: ingress-nginx
    version: "4.10.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress-nginx-ui
    condition: ingress-nginx-ui.enabled
  - name: spark-operator
    version: "2.5.0"
    repository: "https://kubeflow.github.io/spark-operator"
  - name: promtail
    version: "6.16.6"
    repository: "https://grafana.github.io/helm-charts"
