apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if .Values.domains.hub }}orchestration-hub-ingress{{ else }}orchestration-hub-ingress-nip{{ end }}
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIPs.orchestrationHub | quote }}
    networking.gke.io/managed-certificates: {{ if .Values.domains.hub }}"orchestration-hub-ssl"{{ else }}"orchestration-hub-ssl-nip"{{ end }}
spec:
  rules:
    - host: {{ include "zipline-orchestration.orchestrationHubDomain" . }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: orchestration-hub-service
                port:
                  number: {{ .Values.orchestration.hub.port }}