apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if .Values.domains.temporal }}temporal-ui-ingress{{ else }}temporal-ui-ingress-nip{{ end }}
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIPs.temporalUIName | quote }}
    networking.gke.io/managed-certificates: "temporal-ui-ssl"
    networking.gke.io/v1beta1.FrontendConfig: "ingress-frontend-config"
spec:
  rules:
    - host: {{ include "zipline-orchestration.temporalUIDomain" . }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: temporal-web-service
                port:
                  number: 80