apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if .Values.domains.ziplineUI }}orchestration-ui-ingress{{ else }}orchestration-ui-ingress-nip{{ end }}
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIPs.orchestrationUIName | quote }}
    networking.gke.io/managed-certificates: "zipline-ui-ssl"
spec:
  rules:
    - host: {{ include "zipline-orchestration.orchestrationUIDomain" . }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: orchestration-ui-service
                port:
                  number: 80