apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipline-orchestration-hub
  namespace: zipline-system
  labels:
    app: orchestration-hub
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.orchestration.hub.replicas }}
  selector:
    matchLabels:
      app: orchestration-hub
  template:
    metadata:
      labels:
        app: orchestration-hub
    spec:
      serviceAccountName: orchestration-sa
      containers:
        - name: orchestration-hub
          image: "{{ .Values.orchestration.hub.image }}:{{ .Values.global.version }}"
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: "jdbc:postgresql://{{ .Values.database.orchestration.host }}:5432/{{ .Values.database.orchestration.database }}"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orchestration-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orchestration-db-secret
                  key: password
            - name: GCP_REGION
              value: {{ .Values.global.region | quote }}
            - name: GCP_PROJECT_ID
              value: {{ .Values.global.project_id | quote }}
            - name: GCP_BIGTABLE_INSTANCE_ID
              value: {{ .Values.bigtable.instance_id | quote }}
            - name: CUSTOMER_ID
              value: {{ .Values.global.customer_name | quote }}
            - name: ARTIFACT_PREFIX
              value: {{ .Values.global.artifact_prefix | quote }}
            - name: TOPIC_ID
              value: {{ .Values.global.topic_id | quote }}
            - name: TEMPORAL_SERVICE_ADDRESS
              value: "temporal-service:7233"
            - name: TEMPORAL_NAMESPACE
              value: "default"
            - name: ORCHESTRATION_PORT
              value: "{{ .Values.orchestration.hub.port }}"
            - name: TABLE_PARTITIONS_DATASET
              value: "TABLE_PARTITIONS"
          ports:
            - containerPort: {{ .Values.orchestration.hub.port }}
          resources:
          {{- toYaml .Values.orchestration.hub.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: orchestration-hub-service
  namespace: zipline-system
  annotations:
    cloud.google.com/backend-config: '{"default": "orchestration-hub-backendconfig"}'
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  selector:
    app: orchestration-hub
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.orchestration.hub.port }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: orchestration-hub-backendconfig
  namespace: zipline-system
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /ping
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-oauth-credentials