apiVersion: v1
kind: Secret
metadata:
  name: temporal-db-secret
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.database.temporal.host | b64enc | quote }}
  password: {{ .Values.database.temporal.password | b64enc | quote }}
  username: {{ .Values.database.temporal.username | b64enc | quote }}
  database: {{ .Values.database.temporal.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: orchestration-db-secret
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.orchestration.password | b64enc | quote }}
  username: {{ .Values.database.orchestration.username | b64enc | quote }}