apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-sa
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.temporal.googleServiceAccount | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestration-sa
  namespace: zipline-system
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.orchestration.googleServiceAccount | quote }}