apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    service: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app
  template: 
    metadata: 
      labels: 
        service: app
    spec: 
      containers:
        
          - name: app
            image: app-image:canary
            ports:
              - containerPort: 9000
                protocol: TCP
            env:
              - name: JAVA_OPTS
                value: -Xms1g -Xmx1g

            imagePullPolicy: Always

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
  labels:
    service: app
spec:
  ports:
      - name: "9000"
        protocol: TCP
        port: 9000
        targetPort: 9000
  selector:
    service: app
