apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: quickstart-bluegreen
  labels:
    service: quickstart-bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quickstart
  template:
    metadata:
      labels:
        app: quickstart
    spec:
      containers:
        - name: quickstart
          image: quickstart-image:canary
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
  strategy:
    blueGreen:
      activeService: quickstart-bluegreen-active
      previewService: quickstart-bluegreen-preview
      autoPromotionEnabled: true

---
apiVersion: v1
kind: Service
metadata:
  name: quickstart-bluegreen-active
spec:
    selector:
        app: quickstart
    ports:
        - port: 80
          targetPort: 80
    type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: quickstart-bluegreen-preview
spec:
    selector:
        app: quickstart
    ports:
        - port: 80
          targetPort: 80
    type: ClusterIP